name: WND-EMU Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: false # কোনো নষ্ট সাব-মডিউল চেক করবে না
          fetch-depth: 1

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace --no-daemon || echo "Build Failed but checking for APK..."

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WND-EMU-Package
          path: "**/*.apk"
